"""Generates NERVIS-icon.svg — the source `build_icon.sh` rasterises.

Not independent art. The mark is `nervis/src/nervis/pdf.py`'s `_mark()` and
the dashboard's `.brand i` (`nervis/index.html`), redrawn at icon scale: the
same diamond, the same LOGO_EDGE/LOGO_CORE colours from `layout.py`, and the
same idea of a glow behind a solid stroke — the PDF fakes that with three
concentric strokes at falling opacity because PDF has no blur primitive; SVG
does, so this uses one `feGaussianBlur` instead of three shapes.

**The squircle behind it is computed, not approximated.** A hand-built `.app`
with no Xcode asset catalog gets no automatic corner masking from the OS at
render time — Finder and the Dock draw exactly what is in the `.icns` — so
the rounded-square shape every native app icon has has to be drawn here. A
CSS-style `border-radius` rectangle is a circular-arc corner and reads
visibly flatter than Apple's own icons, which use a "squircle": a
superellipse, |x/a|^n + |y/a|^n = 1. n=2 is a circle, n→∞ approaches a sharp
square corner; n=5 sits where Apple's app-icon corner actually sits, and is
computed as a many-point polygon rather than approximated with arcs.
"""

from __future__ import annotations

import math
from pathlib import Path

CANVAS = 1024
CENTER = CANVAS / 2

# The squircle's exponent and how many points trace it. 480 points on a
# 1024px canvas is far more than the curve needs — visually indistinguishable
# from a true smooth superellipse once anti-aliased — but cheap enough that
# there is no reason to hand-tune it down.
SQUIRCLE_EXPONENT = 5.0
SQUIRCLE_POINTS = 480

# The diamond, in `_mark()`'s own terms: `r` is the half-diagonal. The core's
# ratio is bumped from the PDF's r*0.25 — legible in a print at reading
# distance — to r*0.32, which is what stays a recognisable dot once the icon
# is downsampled to 16px for a Finder list view.
DIAMOND_R = 300.0
CORE_RATIO = 0.32
STROKE_WIDTH = 36.0

LOGO_EDGE = "#55DCFF"  # rgb(85, 220, 255) — layout.py's LOGO_EDGE
LOGO_CORE = "#34E6F2"  # layout.py's LOGO_CORE, the dashboard's --cyan
BG_TOP = "#111821"     # --panel
BG_BOTTOM = "#07090d"  # --bg


def squircle_points(size: float = CANVAS, exponent: float = SQUIRCLE_EXPONENT,
                     n: int = SQUIRCLE_POINTS) -> str:
    """The superellipse boundary, as an SVG polygon point list."""
    a = size / 2
    points = []
    for i in range(n):
        t = 2 * math.pi * i / n
        ct, st = math.cos(t), math.sin(t)
        x = a * (1 if ct >= 0 else -1) * abs(ct) ** (2 / exponent)
        y = a * (1 if st >= 0 else -1) * abs(st) ** (2 / exponent)
        points.append((round(a + x, 2), round(a + y, 2)))
    return " ".join(f"{x},{y}" for x, y in points)


def diamond_points(r: float, cx: float = CENTER, cy: float = CENTER) -> str:
    return f"{cx},{cy - r} {cx + r},{cy} {cx},{cy + r} {cx - r},{cy}"


def build() -> str:
    squircle = squircle_points()
    outer = diamond_points(DIAMOND_R)
    core = diamond_points(DIAMOND_R * CORE_RATIO)
    return f'''<!--
  NERVIS.app icon source — generated by generate_icon.py. Edit that file and
  re-run it (or ./build_icon.sh, which calls it) rather than hand-editing the
  polygon points below.
-->
<svg xmlns="http://www.w3.org/2000/svg" width="{CANVAS}" height="{CANVAS}" viewBox="0 0 {CANVAS} {CANVAS}">
 <defs>
  <clipPath id="squircle"><polygon points="{squircle}"/></clipPath>
  <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
   <stop offset="0" stop-color="{BG_TOP}"/>
   <stop offset="1" stop-color="{BG_BOTTOM}"/>
  </linearGradient>
  <filter id="glow" x="-60%" y="-60%" width="220%" height="220%">
   <feGaussianBlur stdDeviation="22"/>
  </filter>
  <filter id="coreglow" x="-100%" y="-100%" width="300%" height="300%">
   <feGaussianBlur stdDeviation="14"/>
  </filter>
 </defs>
 <g clip-path="url(#squircle)">
  <polygon points="{squircle}" fill="url(#bg)"/>
  <polygon points="{outer}" fill="none" stroke="{LOGO_EDGE}" stroke-width="{STROKE_WIDTH}"
    filter="url(#glow)" opacity="0.55"/>
  <polygon points="{core}" fill="{LOGO_CORE}" filter="url(#coreglow)" opacity="0.5"/>
  <polygon points="{outer}" fill="none" stroke="{LOGO_EDGE}" stroke-width="{STROKE_WIDTH}"
    stroke-linejoin="round"/>
  <polygon points="{core}" fill="{LOGO_CORE}"/>
 </g>
</svg>
'''


if __name__ == "__main__":
    out = Path(__file__).parent / "NERVIS-icon.svg"
    out.write_text(build())
    print(f"wrote {out}")
